"use server"

import { createSupabaseServer } from "@/lib/supabase/server"
import { revalidatePath } from "next/cache"
import { redirect } from "next/navigation"

export async function addApplicant(formData: FormData) {
  const supabase = await createSupabaseServer()
  await supabase.from("applicants").insert({
    first_name: formData.get("first_name") as string,
    last_name: formData.get("last_name") as string,
    middle_name: (formData.get("middle_name") as string) || null,
    position_applied: formData.get("position_applied") as string,
    status: (formData.get("status") as string) || "For Processing",
    contact_number: (formData.get("contact_number") as string) || null,
    email: (formData.get("email") as string) || null,
    years_of_exp: Number(formData.get("years_of_exp")) || 0,
    skills: (formData.get("skills") as string) || null,
    notes: (formData.get("notes") as string) || null,

    second_choice_position: formData.get("second_choice_position") as string,
    preferred_branch: formData.get("preferred_branch") as string,
    country_applying_for: formData.get("country_applying_for") as string,
    current_address: formData.get("current_address") as string,
    provincial_address: formData.get("provincial_address") as string,
    active_cellphone: formData.get("active_cellphone") as string,
    active_email: formData.get("active_email") as string,
    date_of_birth: formData.get("date_of_birth") || null,
    age: Number(formData.get("age")) || null,
    place_of_birth: formData.get("place_of_birth") as string,
    religion: formData.get("religion") as string,
    civil_status: formData.get("civil_status") as string,
    height_cm: Number(formData.get("height_cm")) || null,
    weight_kg: Number(formData.get("weight_kg")) || null,
    facebook_account: formData.get("facebook_account") as string,
    mother_full_name: formData.get("mother_full_name") as string,
    mother_contact: formData.get("mother_contact") as string,
    father_full_name: formData.get("father_full_name") as string,
    father_contact: formData.get("father_contact") as string,
    spouse_name: formData.get("spouse_name") as string,
    spouse_age: Number(formData.get("spouse_age")) || null,
    spouse_contact: formData.get("spouse_contact") as string,
    number_of_children: Number(formData.get("number_of_children")) || null,
    children_ages: formData.get("children_ages") as string,
    children_caretaker: formData.get("children_caretaker") as string,
    emergency_contact_name: formData.get("emergency_contact_name") as string,
    emergency_contact_relationship: formData.get("emergency_contact_relationship") as string,
    emergency_contact_number: formData.get("emergency_contact_number") as string,
    emergency_contact_address: formData.get("emergency_contact_address") as string,

    beneficiary1_name: formData.get("beneficiary1_name") as string,
    beneficiary1_dob: formData.get("beneficiary1_dob") || null,
    beneficiary1_age: Number(formData.get("beneficiary1_age")) || null,
    beneficiary1_relationship: formData.get("beneficiary1_relationship") as string,
    beneficiary1_contact: formData.get("beneficiary1_contact") as string,
    beneficiary2_name: formData.get("beneficiary2_name") as string,
    beneficiary2_dob: formData.get("beneficiary2_dob") || null,
    beneficiary2_age: Number(formData.get("beneficiary2_age")) || null,
    beneficiary2_relationship: formData.get("beneficiary2_relationship") as string,
    beneficiary2_contact: formData.get("beneficiary2_contact") as string,

    elementary_school: formData.get("elementary_school") as string,
    elementary_address: formData.get("elementary_address") as string,
    elementary_year_graduated: formData.get("elementary_year_graduated") as string,
    high_school: formData.get("high_school") as string,
    high_school_address: formData.get("high_school_address") as string,
    high_school_year_graduated: formData.get("high_school_year_graduated") as string,
    vocational_course: formData.get("vocational_course") as string,
    vocational_school: formData.get("vocational_school") as string,
    vocational_year_graduated: formData.get("vocational_year_graduated") as string,
    college_course: formData.get("college_course") as string,
    college_school: formData.get("college_school") as string,
    college_year_graduated: formData.get("college_year_graduated") as string,

    work1_country: formData.get("work1_country") as string,
    work1_company: formData.get("work1_company") as string,
    work1_position: formData.get("work1_position") as string,
    work1_date_started: formData.get("work1_date_started") || null,
    work1_date_ended: formData.get("work1_date_ended") || null,
    work2_country: formData.get("work2_country") as string,
    work2_company: formData.get("work2_company") as string,
    work2_position: formData.get("work2_position") as string,
    work2_date_started: formData.get("work2_date_started") || null,
    work2_date_ended: formData.get("work2_date_ended") || null,
    work3_country: formData.get("work3_country") as string,
    work3_company: formData.get("work3_company") as string,
    work3_position: formData.get("work3_position") as string,
    work3_date_started: formData.get("work3_date_started") || null,
    work3_date_ended: formData.get("work3_date_ended") || null,

    english_level: formData.get("english_level") as string,
    arabic_level: formData.get("arabic_level") as string,
    passport_number: formData.get("passport_number") as string,
    passport_date_issued: formData.get("passport_date_issued") || null,
    passport_date_expired: formData.get("passport_date_expired") || null,
    passport_place_issued: formData.get("passport_place_issued") as string,

    interview_remarks: formData.get("interview_remarks") as string,
    interviewer_name: formData.get("interviewer_name") as string,
    date_interviewed: formData.get("date_interviewed") || null
  })

  revalidatePath("/applicants")
  redirect("/applicants")
}
export async function updateApplicant(formData: FormData) {
  const supabase = await createSupabaseServer()
  const id = Number(formData.get("id"))
  if (!id) redirect("/applicants")

  await supabase.from("applicants").update({
    first_name: formData.get("first_name") as string,
    last_name: formData.get("last_name") as string,
    middle_name: (formData.get("middle_name") as string) || null,
    position_applied: formData.get("position_applied") as string,
    status: formData.get("status") as string,
    contact_number: (formData.get("contact_number") as string) || null,
    email: (formData.get("email") as string) || null,
    years_of_exp: Number(formData.get("years_of_exp")) || 0,
    skills: (formData.get("skills") as string) || null,
    notes: (formData.get("notes") as string) || null,

    second_choice_position: formData.get("second_choice_position") as string,
    preferred_branch: formData.get("preferred_branch") as string,
    country_applying_for: formData.get("country_applying_for") as string,
    current_address: formData.get("current_address") as string,
    provincial_address: formData.get("provincial_address") as string,
    active_cellphone: formData.get("active_cellphone") as string,
    active_email: formData.get("active_email") as string,
    date_of_birth: formData.get("date_of_birth") || null,
    age: Number(formData.get("age")) || null,
    place_of_birth: formData.get("place_of_birth") as string,
    religion: formData.get("religion") as string,
    civil_status: formData.get("civil_status") as string,
    height_cm: Number(formData.get("height_cm")) || null,
    weight_kg: Number(formData.get("weight_kg")) || null,
    facebook_account: formData.get("facebook_account") as string,
    mother_full_name: formData.get("mother_full_name") as string,
    mother_contact: formData.get("mother_contact") as string,
    father_full_name: formData.get("father_full_name") as string,
    father_contact: formData.get("father_contact") as string,
    spouse_name: formData.get("spouse_name") as string,
    spouse_age: Number(formData.get("spouse_age")) || null,
    spouse_contact: formData.get("spouse_contact") as string,
    number_of_children: Number(formData.get("number_of_children")) || null,
    children_ages: formData.get("children_ages") as string,
    children_caretaker: formData.get("children_caretaker") as string,
    emergency_contact_name: formData.get("emergency_contact_name") as string,
    emergency_contact_relationship: formData.get("emergency_contact_relationship") as string,
    emergency_contact_number: formData.get("emergency_contact_number") as string,
    emergency_contact_address: formData.get("emergency_contact_address") as string,

    beneficiary1_name: formData.get("beneficiary1_name") as string,
    beneficiary1_dob: formData.get("beneficiary1_dob") || null,
    beneficiary1_age: Number(formData.get("beneficiary1_age")) || null,
    beneficiary1_relationship: formData.get("beneficiary1_relationship") as string,
    beneficiary1_contact: formData.get("beneficiary1_contact") as string,
    beneficiary2_name: formData.get("beneficiary2_name") as string,
    beneficiary2_dob: formData.get("beneficiary2_dob") || null,
    beneficiary2_age: Number(formData.get("beneficiary2_age")) || null,
    beneficiary2_relationship: formData.get("beneficiary2_relationship") as string,
    beneficiary2_contact: formData.get("beneficiary2_contact") as string,

    elementary_school: formData.get("elementary_school") as string,
    elementary_address: formData.get("elementary_address") as string,
    elementary_year_graduated: formData.get("elementary_year_graduated") as string,
    high_school: formData.get("high_school") as string,
    high_school_address: formData.get("high_school_address") as string,
    high_school_year_graduated: formData.get("high_school_year_graduated") as string,
    vocational_course: formData.get("vocational_course") as string,
    vocational_school: formData.get("vocational_school") as string,
    vocational_year_graduated: formData.get("vocational_year_graduated") as string,
    college_course: formData.get("college_course") as string,
    college_school: formData.get("college_school") as string,
    college_year_graduated: formData.get("college_year_graduated") as string,

    work1_country: formData.get("work1_country") as string,
    work1_company: formData.get("work1_company") as string,
    work1_position: formData.get("work1_position") as string,
    work1_date_started: formData.get("work1_date_started") || null,
    work1_date_ended: formData.get("work1_date_ended") || null,
    work2_country: formData.get("work2_country") as string,
    work2_company: formData.get("work2_company") as string,
    work2_position: formData.get("work2_position") as string,
    work2_date_started: formData.get("work2_date_started") || null,
    work2_date_ended: formData.get("work2_date_ended") || null,
    work3_country: formData.get("work3_country") as string,
    work3_company: formData.get("work3_company") as string,
    work3_position: formData.get("work3_position") as string,
    work3_date_started: formData.get("work3_date_started") || null,
    work3_date_ended: formData.get("work3_date_ended") || null,

    english_level: formData.get("english_level") as string,
    arabic_level: formData.get("arabic_level") as string,
    passport_number: formData.get("passport_number") as string,
    passport_date_issued: formData.get("passport_date_issued") || null,
    passport_date_expired: formData.get("passport_date_expired") || null,
    passport_place_issued: formData.get("passport_place_issued") as string,

    interview_remarks: formData.get("interview_remarks") as string,
    interviewer_name: formData.get("interviewer_name") as string,
    date_interviewed: formData.get("date_interviewed") || null
  }).eq("id", id)

  revalidatePath("/applicants")
  revalidatePath(`/applicants/${id}`)
  redirect("/applicants")
}